name: robot
task:
    type: FlatEvadeTask
    spec: {}
model:
    planning:
      # for single dimension
      type: DoubleIntegrator
      spec:
        state_component: ['pos', 'vel']
    control:
      type: BallModel
      spec:
          control_input_dim: 2
      # type: UnicycleModel
      # spec:
      #     control_input_dim: 2
cycle_time: 0.1
planner:
    type: NaivePlanner
    spec:
        horizon: 20
        replanning_cycle: 10
        state_dimension: 2
controller:
    type: Controller
    spec:
        feedback_controller: 
          type: NaiveFeedbackController
          spec:
            kp: 400
            kv: 80
            u_max: [500, 500]
        safe_controller: 
          # type: UnsafeController
          type: SafeSetController
        #   type: ZeroingBarrierFunctionController
          # type: SublevelSafeSetController
          # type: UnsafeController
          # type: PotentialFieldController
          # type: SlidingModeController
          spec:
              d_min: 15.0
              k_v: 5.0
              eta: 1
              c: 1000
              lambd: 1
              u_max: [200, 200]
estimator:
    type: NaiveEstimator
    spec:
        init_x: [50.0, 20.0, 0.0, 0.0]
        init_variance: [0.01, 0.01, 0.01, 0.01]
        Rww: [0.001, 0.001, 0.001, 0.001]
        Rvv: [0.001, 0.001, 0.001, 0.001]
        alpha_ukf: 1
        kappa_ukf: 0.1
        beta_ukf: 2
        time_sample: 0.01
        kp: 40
        kv: 40
sensors:
-   type: PVSensor
    spec:
        alias: cartesian_sensor
        noise_var: 0.0
-   type: StateSensor
    spec:
        alias: state_sensor
        noise_var: 0.1
-   type: RadarSensor
    spec:
        alias: obstacle_sensor
        noise_var: 0.1
-   type: GoalSensor
    spec:
        alias: goal_sensor
        noise_var: 0.1
-   type: RadioSensor
    spec:
        alias: communication_sensor