name: robot
task:
    type: FlatReachingTask
    spec: {}
model:
    planning:
      # for single dimension
      type: DoubleIntegrator
      spec:
          dT: 0.02
          state_component: ['pos', 'vel']
    control:
      # type: BallModel
      # spec:
      #     control_input_dim: 2
      type: UnicycleModel
      spec:
          control_input_dim: 2
planner:
    type: IntegraterPlanner
    spec:
        horizon: 50
        replanning_cycle: 10
        state_dimension: 2
    # type: NaivePlanner
    # spec:
    #     horizon: 20
    #     replanning_cycle: 10
    #     state_dimension: 2
    #     n_ob: 1
    #     obs_r: 5
controller:
    type: Controller
    spec:
        feedback_controller: 
            type: NaiveFeedbackController
            spec:
                # for naive planner
                # kp: 200
                # kv: 50
                # for integrator planner
                kp: 200
                kv: 100
                u_max: [0.01, 10]
        safe_controller:
            # TODO type ISSA
            type: ISSAController
            # type: UnsafeController
            # type: SafeSetController
            # type: ZeroingBarrierFunctionController
            # type: SublevelSafeSetController
            # type: UnsafeController
            # type: PotentialFieldController
            # type: SlidingModeController
            spec:
                d_min: 15.0
                k_v: 5.0
                eta: 1
                c: 1000
                lambd: 1
                u_max: [1000, 1000]
estimator:
    type: NaiveEstimator
    spec:
        init_x: [50.0, 20.0, 0.0, 0.0]
        init_variance: [0.01, 0.01, 0.01, 0.01]
        Rww: [0.001, 0.001, 0.001, 0.001]
        Rvv: [0.001, 0.001, 0.001, 0.001]
        alpha_ukf: 1
        kappa_ukf: 0.1
        beta_ukf: 2
        time_sample: 0.01
        kp: 40
        kv: 40
sensors:
-   type: PVSensor
    spec:
        alias: cartesian_sensor
        noise_var: 0.001
-   type: StateSensor
    spec:
        alias: state_sensor
        noise_var: 0.001
-   type: RadarSensor
    spec:
        alias: obstacle_sensor
        noise_var: 0.001
-   type: GoalSensor
    spec:
        alias: goal_sensor
        noise_var: 0.001

